#!/usr/bin/env python3
from pathlib import Path
import json,hashlib
ROOT=Path(__file__).resolve().parents[1]
checks={}
def add(k,v):checks[k]=bool(v)
seal=(ROOT/"scripts/t1gr_e4_seal_split.py").read_text(encoding="utf-8")
ver=(ROOT/"scripts/t1gr_e4_verify_seal.py").read_text(encoding="utf-8")
pol=json.loads((ROOT/"config/t1gr_e4_seal_policy.json").read_text())
add("reviewed_commit_pinned",len(pol["reviewed_e3"]["commit_full"])==40)
add("split_public_sha_pinned",len(pol["reviewed_e3"]["split_public_sha256"])==64)
add("closure_public_sha_pinned",len(pol["reviewed_e3"]["closure_public_sha256"])==64)
add("three_id_commitments_pinned",set(pol["reviewed_e3"]["ids_commitments"])=={"train","dev","final_holdout"})
add("reviewed_counts_pinned",pol["reviewed_e3"]["counts"]=={"train":1504,"dev":198,"final_holdout":298})
add("separate_train_dev_artifact","train-dev-access-out" in seal)
add("separate_holdout_artifact","final-holdout-sealed-out" in seal)
add("no_master_all_ids_output","split-manifest-private" not in seal)
add("private_input_guard","ensure_private_input" in seal)
add("private_output_guard","ensure_private_output" in seal)
add("public_guard","ensure_public_output" in seal)
add("public_sensitive_scanner","assert_public_safe(public)" in seal)
add("atomic_write","atomic_json_write" in seal)
add("concurrency_lock","file_lock" in seal)
add("timeout","Deadline" in seal)
add("input_change_guard","require_unchanged" in seal)
add("git_ancestor_check","merge-base" in seal and "--is-ancestor" in seal)
add("payload_integrity","payload_ok" in seal)
add("component_resplit_check","COMPONENT_SPLIT_DETECTED" in seal)
add("historical_quarantine_check","HISTORICAL_QUARANTINE_VIOLATION" in seal)
add("final_holdout_not_in_train_dev","final_holdout_ids_sha256" in seal and "final_holdout_ids\":" not in seal.split("train_dev={",1)[1].split("holdout={",1)[0])
add("e4_does_not_authorize_training","step1_training_authorized\":False" in seal)
add("verify_disjoint","E4_SPLIT_OVERLAP" in ver)
add("verify_union","E4_SPLIT_UNION_NOT_2000" in ver)
add("verify_private_sha","TRAIN_DEV_ARTIFACT_SHA_DRIFT" in ver and "HOLDOUT_ARTIFACT_SHA_DRIFT" in ver)
add("verify_holdout_policy","HOLDOUT_OPEN_POLICY_DRIFT" in ver)
add("verify_no_ids_public","assert_public_safe(report)" in ver)
passed=sum(checks.values());report={"schema":"t1gr-e4-static-audit-v1","checks":checks,"passed":passed,"total":len(checks),"all_passed":passed==len(checks)}
out=ROOT/"reports/step4_t1gr/e4_static_audit.json";out.parent.mkdir(parents=True,exist_ok=True);out.write_text(json.dumps(report,indent=2),encoding="utf-8")
print(json.dumps(report,indent=2))
if not report["all_passed"]:raise SystemExit(2)
